<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>ICSharpCode.TextEditor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ICSharpCode.TextEditor.Resources.ASPX.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.BAT-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.CPP-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.Coco-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.CSharp-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.HTML-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.Java-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.JavaScript-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.PHP-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.Tex-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.VBNET-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.XML-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.Boo.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.Patch-Mode.xshd" />
    <None Remove="ICSharpCode.TextEditor.Resources.TextEditorControl.bmp" />
    <None Remove="ICSharpCode.TextEditor.Resources.Mode.xsd" />
    <None Remove="ICSharpCode.TextEditor.Resources.RightArrow.cur" />
    <None Remove="ICSharpCode.TextEditor.Resources.SyntaxModes.xml" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.ASPX.xshd" LogicalName="ICSharpCode.TextEditor.Resources.ASPX.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.BAT-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.BAT-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.CPP-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.CPP-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Coco-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.Coco-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.CSharp-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.CSharp-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.HTML-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.HTML-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Java-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.Java-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.JavaScript-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.JavaScript-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.PHP-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.PHP-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Tex-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.Tex-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.VBNET-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.VBNET-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.XML-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.XML-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Boo.xshd" LogicalName="ICSharpCode.TextEditor.Resources.Boo.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Patch-Mode.xshd" LogicalName="ICSharpCode.TextEditor.Resources.Patch-Mode.xshd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.TextEditorControl.bmp" LogicalName="ICSharpCode.TextEditor.Resources.TextEditorControl.bmp" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.Mode.xsd" LogicalName="ICSharpCode.TextEditor.Resources.Mode.xsd" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.RightArrow.cur" LogicalName="ICSharpCode.TextEditor.Resources.RightArrow.cur" />
    <EmbeddedResource Include="ICSharpCode.TextEditor.Resources.SyntaxModes.xml" LogicalName="ICSharpCode.TextEditor.Resources.SyntaxModes.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>