using System;

namespace dnSpy.Contracts.Decompiler;

[Flags]
public enum CodeBracesRangeFlags
{
	BraceKind_None = 0,
	BraceKind_Parentheses = 1,
	BraceKind_CurlyBraces = 2,
	BraceKind_SquareBrackets = BraceKind_Parentheses | BraceKind_CurlyBraces,
	BraceKind_AngleBrackets = 4,
	BraceKind_DoubleQuotes = BraceKind_Parentheses | BraceKind_AngleBrackets,
	BraceKind_SingleQuotes = BraceKind_CurlyBraces | BraceKind_AngleBrackets,
	BraceKind_OtherBraces = BraceKind_SquareBrackets | BraceKind_AngleBrackets,
	BlockKind_None = 0,
	BlockKind_Namespace = 0x100,
	BlockKind_Type = 0x200,
	BlockKind_Module = BlockKind_Namespace | BlockKind_Type,
	BlockKind_ValueType = 0x400,
	BlockKind_Interface = BlockKind_Namespace | BlockKind_ValueType,
	BlockKind_Method = BlockKind_Type | BlockKind_ValueType,
	BlockKind_Accessor = BlockKind_Module | BlockKind_ValueType,
	BlockKind_AnonymousMethod = 0x800,
	BlockKind_Constructor = BlockKind_Namespace | BlockKind_AnonymousMethod,
	BlockKind_Destructor = BlockKind_Type | BlockKind_AnonymousMethod,
	BlockKind_Operator = BlockKind_Module | BlockKind_AnonymousMethod,
	BlockKind_Conditional = BlockKind_ValueType | BlockKind_AnonymousMethod,
	BlockKind_Loop = BlockKind_Interface | BlockKind_AnonymousMethod,
	BlockKind_Property = BlockKind_Method | BlockKind_AnonymousMethod,
	BlockKind_Event = BlockKind_Accessor | BlockKind_AnonymousMethod,
	BlockKind_Try = 0x1000,
	BlockKind_Catch = BlockKind_Namespace | BlockKind_Try,
	BlockKind_Filter = BlockKind_Type | BlockKind_Try,
	BlockKind_Finally = BlockKind_Module | BlockKind_Try,
	BlockKind_Fault = BlockKind_ValueType | BlockKind_Try,
	BlockKind_Lock = BlockKind_Interface | BlockKind_Try,
	BlockKind_Using = BlockKind_Method | BlockKind_Try,
	BlockKind_Fixed = BlockKind_Accessor | BlockKind_Try,
	BlockKind_Switch = BlockKind_AnonymousMethod | BlockKind_Try,
	BlockKind_Case = BlockKind_Constructor | BlockKind_Try,
	BlockKind_LocalFunction = BlockKind_Destructor | BlockKind_Try,
	BlockKind_Other = BlockKind_Operator | BlockKind_Try,
	BlockKind_Xml = BlockKind_Conditional | BlockKind_Try,
	BlockKind_Xaml = BlockKind_Loop | BlockKind_Try,
	NamespaceBraces = BraceKind_CurlyBraces | BlockKind_Namespace,
	TypeBraces = BraceKind_CurlyBraces | BlockKind_Type,
	ModuleBraces = BlockKind_Module | BraceKind_CurlyBraces,
	ValueTypeBraces = BraceKind_CurlyBraces | BlockKind_ValueType,
	InterfaceBraces = BlockKind_Interface | BraceKind_CurlyBraces,
	MethodBraces = BlockKind_Method | BraceKind_CurlyBraces,
	AccessorBraces = BlockKind_Accessor | BraceKind_CurlyBraces,
	AnonymousMethodBraces = BraceKind_CurlyBraces | BlockKind_AnonymousMethod,
	ConstructorBraces = BlockKind_Constructor | BraceKind_CurlyBraces,
	DestructorBraces = BlockKind_Destructor | BraceKind_CurlyBraces,
	OperatorBraces = BlockKind_Operator | BraceKind_CurlyBraces,
	ConditionalBraces = BlockKind_Conditional | BraceKind_CurlyBraces,
	LoopBraces = BlockKind_Loop | BraceKind_CurlyBraces,
	PropertyBraces = BlockKind_Property | BraceKind_CurlyBraces,
	EventBraces = BlockKind_Event | BraceKind_CurlyBraces,
	TryBraces = BraceKind_CurlyBraces | BlockKind_Try,
	CatchBraces = BlockKind_Catch | BraceKind_CurlyBraces,
	FilterBraces = BlockKind_Filter | BraceKind_CurlyBraces,
	FinallyBraces = BlockKind_Finally | BraceKind_CurlyBraces,
	FaultBraces = BlockKind_Fault | BraceKind_CurlyBraces,
	LockBraces = BlockKind_Lock | BraceKind_CurlyBraces,
	UsingBraces = BlockKind_Using | BraceKind_CurlyBraces,
	FixedBraces = BlockKind_Fixed | BraceKind_CurlyBraces,
	SwitchBraces = BlockKind_Switch | BraceKind_CurlyBraces,
	CaseBraces = BlockKind_Case | BraceKind_CurlyBraces,
	LocalFunctionBraces = BlockKind_LocalFunction | BraceKind_CurlyBraces,
	OtherBlockBraces = BlockKind_Other | BraceKind_CurlyBraces,
	XmlBlockBraces = BraceKind_OtherBraces | BlockKind_Xml,
	XamlBlockBraces = XmlBlockBraces | BlockKind_Namespace,
	SingleQuotes = 6,
	DoubleQuotes = 5,
	Parentheses = BraceKind_Parentheses,
	AngleBrackets = BraceKind_AngleBrackets,
	SquareBrackets = 3,
	CurlyBraces = BraceKind_CurlyBraces,
	OtherBraces = 7
}
