<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Runtime.Serialization.Primitives</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="System.Runtime.Serialization.Primitives.Resources.System.Runtime.Serialization.Primitives.rd.xml" />
    <EmbeddedResource Include="System.Runtime.Serialization.Primitives.Resources.System.Runtime.Serialization.Primitives.rd.xml" LogicalName="System.Runtime.Serialization.Primitives.Resources.System.Runtime.Serialization.Primitives.rd.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>
</Project>