using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Xml.Serialization;

[assembly: AssemblyTitle("System.Xml.XmlSerializer")]
[assembly: AssemblyDescription("System.Xml.XmlSerializer")]
[assembly: AssemblyDefaultAlias("System.Xml.XmlSerializer")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("4.6.25714.01")]
[assembly: AssemblyInformationalVersion("4.6.25714.01 built by: dlab-DDVSOWINAGE032. Commit Hash: b7f182415927d3b98445d043e1680c56b9d1f17c")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyMetadata("", "")]
[assembly: AssemblyVersion("4.0.11.0")]
[assembly: TypeForwardedTo(typeof(IXmlSerializable))]
[assembly: TypeForwardedTo(typeof(XmlAnyAttributeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAnyElementAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAnyElementAttributes))]
[assembly: TypeForwardedTo(typeof(XmlArrayAttribute))]
[assembly: TypeForwardedTo(typeof(XmlArrayItemAttribute))]
[assembly: TypeForwardedTo(typeof(XmlArrayItemAttributes))]
[assembly: TypeForwardedTo(typeof(XmlAttributeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlAttributeOverrides))]
[assembly: TypeForwardedTo(typeof(XmlAttributes))]
[assembly: TypeForwardedTo(typeof(XmlChoiceIdentifierAttribute))]
[assembly: TypeForwardedTo(typeof(XmlElementAttribute))]
[assembly: TypeForwardedTo(typeof(XmlElementAttributes))]
[assembly: TypeForwardedTo(typeof(XmlEnumAttribute))]
[assembly: TypeForwardedTo(typeof(XmlIgnoreAttribute))]
[assembly: TypeForwardedTo(typeof(XmlIncludeAttribute))]
[assembly: TypeForwardedTo(typeof(XmlNamespaceDeclarationsAttribute))]
[assembly: TypeForwardedTo(typeof(XmlRootAttribute))]
[assembly: TypeForwardedTo(typeof(XmlSchemaProviderAttribute))]
[assembly: TypeForwardedTo(typeof(XmlSerializer))]
[assembly: TypeForwardedTo(typeof(XmlSerializerNamespaces))]
[assembly: TypeForwardedTo(typeof(XmlTextAttribute))]
[assembly: TypeForwardedTo(typeof(XmlTypeAttribute))]
