using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Win32.SafeHandles;

[assembly: AssemblyTitle("System.Security.Cryptography.X509Certificates")]
[assembly: AssemblyDescription("System.Security.Cryptography.X509Certificates")]
[assembly: AssemblyDefaultAlias("System.Security.Cryptography.X509Certificates")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("4.6.25714.01")]
[assembly: AssemblyInformationalVersion("4.6.25714.01 built by: dlab-DDVSOWINAGE032. Commit Hash: b7f182415927d3b98445d043e1680c56b9d1f17c")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyMetadata("", "")]
[assembly: AssemblyVersion("4.1.2.0")]
[assembly: TypeForwardedTo(typeof(SafeX509ChainHandle))]
[assembly: TypeForwardedTo(typeof(ECDsaCertificateExtensions))]
[assembly: TypeForwardedTo(typeof(OpenFlags))]
[assembly: TypeForwardedTo(typeof(PublicKey))]
[assembly: TypeForwardedTo(typeof(RSACertificateExtensions))]
[assembly: TypeForwardedTo(typeof(StoreLocation))]
[assembly: TypeForwardedTo(typeof(StoreName))]
[assembly: TypeForwardedTo(typeof(X500DistinguishedName))]
[assembly: TypeForwardedTo(typeof(X500DistinguishedNameFlags))]
[assembly: TypeForwardedTo(typeof(X509BasicConstraintsExtension))]
[assembly: TypeForwardedTo(typeof(X509Certificate))]
[assembly: TypeForwardedTo(typeof(X509Certificate2))]
[assembly: TypeForwardedTo(typeof(X509Certificate2Collection))]
[assembly: TypeForwardedTo(typeof(X509Certificate2Enumerator))]
[assembly: TypeForwardedTo(typeof(X509CertificateCollection))]
[assembly: TypeForwardedTo(typeof(X509Chain))]
[assembly: TypeForwardedTo(typeof(X509ChainElement))]
[assembly: TypeForwardedTo(typeof(X509ChainElementCollection))]
[assembly: TypeForwardedTo(typeof(X509ChainElementEnumerator))]
[assembly: TypeForwardedTo(typeof(X509ChainPolicy))]
[assembly: TypeForwardedTo(typeof(X509ChainStatus))]
[assembly: TypeForwardedTo(typeof(X509ChainStatusFlags))]
[assembly: TypeForwardedTo(typeof(X509ContentType))]
[assembly: TypeForwardedTo(typeof(X509EnhancedKeyUsageExtension))]
[assembly: TypeForwardedTo(typeof(X509Extension))]
[assembly: TypeForwardedTo(typeof(X509ExtensionCollection))]
[assembly: TypeForwardedTo(typeof(X509ExtensionEnumerator))]
[assembly: TypeForwardedTo(typeof(X509FindType))]
[assembly: TypeForwardedTo(typeof(X509KeyStorageFlags))]
[assembly: TypeForwardedTo(typeof(X509KeyUsageExtension))]
[assembly: TypeForwardedTo(typeof(X509KeyUsageFlags))]
[assembly: TypeForwardedTo(typeof(X509NameType))]
[assembly: TypeForwardedTo(typeof(X509RevocationFlag))]
[assembly: TypeForwardedTo(typeof(X509RevocationMode))]
[assembly: TypeForwardedTo(typeof(X509Store))]
[assembly: TypeForwardedTo(typeof(X509SubjectKeyIdentifierExtension))]
[assembly: TypeForwardedTo(typeof(X509SubjectKeyIdentifierHashAlgorithm))]
[assembly: TypeForwardedTo(typeof(X509VerificationFlags))]
