<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>dnSpy.Decompiler.ILSpy.x</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="themes\wpf.styles.templates.baml" />
    <EmbeddedResource Include="themes\wpf.styles.templates.baml" LogicalName="themes/wpf.styles.templates.baml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WindowsBase" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="Microsoft.VisualStudio.CoreUtility" />
    <Reference Include="dnSpy.Contracts.DnSpy" />
    <Reference Include="System.Core" />
    <ProjectReference Include="..\dnSpy.Contracts.Logic\dnSpy.Contracts.Logic.csproj" />
    <ProjectReference Include="..\dnSpy.Decompiler.ILSpy.Core\dnSpy.Decompiler.ILSpy.Core.csproj" />
    <ProjectReference Include="..\ICSharpCode.Decompiler\ICSharpCode.Decompiler.csproj" />
    <ProjectReference Include="..\dnlib\dnlib.csproj" />
  </ItemGroup>
</Project>