using System.Diagnostics;

namespace AssetRipper.Il2CppRestore.StructDb.Generator;

/// <summary>
/// Runs clang (bundled with every Unity Editor install, under
/// <c>Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/&lt;host&gt;/bin/</c>) against
/// the matching <c>libil2cpp</c> headers to measure real struct layouts — guide §10.2. This is an
/// offline, once-per-(Unity version, target triple) tool, never something the restore pipeline itself
/// invokes at runtime. It is the C# equivalent of the guide's own <c>tools/structdb_gen.py</c>, not a
/// wrapper around it — that script's Python is not available to translate line-for-line here, only its
/// documented behavior (three clang passes, JSON schema, two-round verification).
/// </summary>
public static class StructDbGenerator
{
	/// <summary>
	/// Structs worth forcing clang to lay out. Extend this list as the lifter starts needing more of
	/// them resolved through <see cref="StructDb.TryResolveField"/>.
	/// </summary>
	private static readonly string[] StructsToProbe =
	[
		"Il2CppObject", "Il2CppClass", "Il2CppString", "Il2CppArray", "MethodInfo", "Il2CppTypeDefinition",
		"Il2CppType", "Il2CppAssembly", "Il2CppAssemblyName", "Il2CppImage",
	];

	/// <summary>Only clang decls whose name plausibly belongs to IL2CPP are kept — guide §10.2 trap #7: never filter by "libil2cpp" appearing in the location, only by name.</summary>
	private static bool IsIl2CppName(string name) =>
		name.StartsWith("Il2Cpp", StringComparison.Ordinal) || name.StartsWith("kIl2Cpp", StringComparison.Ordinal);

	public static StructDbFile Generate(string clangPath, string libil2cppIncludeDir, string target, string unityVersion, int metadataVersion)
	{
		string workDir = Directory.CreateTempSubdirectory("il2cpp-restore-structdb-").FullName;
		try
		{
			int pointerSize = IsPointerSize4(target) ? 4 : 8;

			// Pass 1: struct/union layout.
			string layoutsText = RunClang(clangPath, libil2cppIncludeDir, target, workDir, "layout.cpp",
				BuildLayoutProbeSource(), "-Xclang", "-fdump-record-layouts", "-c", "-o", "probe.o");
			Dictionary<string, StructInfo> structs = ClangLayoutParser.Parse(layoutsText, pointerSize);

			// Pass 2: enum values and typedef targets — invisible to -fdump-record-layouts.
			string astDumpText = RunClang(clangPath, libil2cppIncludeDir, target, workDir, "ast.cpp",
				BuildIncludeOnlySource(), "-Xclang", "-ast-dump", "-fsyntax-only");
			Dictionary<string, string> enums = AstDumpParser.ParseEnums(astDumpText, IsIl2CppName);
			Dictionary<string, string> typedefs = AstDumpParser.ParseTypedefs(astDumpText, IsIl2CppName);

			// Pass 3: object-like macros (e.g. IL2CPP_ZERO_LEN_ARRAY).
			string macroText = RunClang(clangPath, libil2cppIncludeDir, target, workDir, "macro.cpp",
				BuildIncludeOnlySource(), "-dM", "-E");
			Dictionary<string, string> defines = MacroDefineParser.Parse(macroText, IsIl2CppName);

			return new StructDbFile
			{
				UnityVersion = unityVersion,
				MetadataVersion = metadataVersion,
				PointerSize = pointerSize,
				Source = new StructDbSource { Target = target, Tool = "AssetRipper.Il2CppRestore.StructDb.Generator" },
				Structs = structs,
				Enums = enums,
				Defines = defines,
				Typedefs = typedefs,
			};
		}
		finally
		{
			try
			{
				Directory.Delete(workDir, recursive: true);
			}
			catch (IOException)
			{
				// Best-effort cleanup; a leftover temp directory is harmless.
			}
		}
	}

	private static bool IsPointerSize4(string target) =>
		target.StartsWith("i386", StringComparison.Ordinal) || target.StartsWith("armv7", StringComparison.Ordinal);

	private static string BuildIncludeOnlySource()
	{
		return """
			// Generated by AssetRipper.Il2CppRestore.StructDb.Generator
			#include "il2cpp-config.h"
			#include "il2cpp-class-internals.h"
			#include "il2cpp-object-internals.h"
			#include "vm/GlobalMetadataFileInternals.h"
			""";
	}

	private static string BuildLayoutProbeSource()
	{
		System.Text.StringBuilder source = new(BuildIncludeOnlySource());
		source.AppendLine();
		source.AppendLine("// A char array's size forces clang to compute the record's full layout without");
		source.AppendLine("// needing to default-construct it — several IL2CPP structs have const members,");
		source.AppendLine("// which deletes the default constructor a plain global variable would need");
		source.AppendLine("// (guide 10.2 trap #2).");
		int i = 0;
		foreach (string name in StructsToProbe)
		{
			source.AppendLine($"char force_{i}[sizeof({name})];");
			source.AppendLine($"char align_{i}[__alignof__({name})];");
			i++;
		}
		source.AppendLine("int main() { return 0; }");
		return source.ToString();
	}

	private static string RunClang(string clangPath, string includeDir, string target, string workDir, string sourceFileName, string sourceText, params string[] extraArgs)
	{
		string sourcePath = Path.Combine(workDir, sourceFileName);
		File.WriteAllText(sourcePath, sourceText);

		ProcessStartInfo startInfo = new(clangPath)
		{
			WorkingDirectory = workDir,
			RedirectStandardOutput = true,
			RedirectStandardError = true,
			UseShellExecute = false,
		};

		// -fsyntax-only alone prints nothing for -fdump-record-layouts; that pass needs -c (or
		// -emit-llvm -S) to actually compute layouts, not just check syntax (guide §10.2 trap #1). The
		// ast-dump and macro passes below use -fsyntax-only/-E instead since they don't need codegen.
		string[] baseArgs = ["-x", "c++", "-std=c++11", "-target", target, "-I", includeDir, "-I", Path.Combine(includeDir, "pch")];
		foreach (string argument in baseArgs)
		{
			startInfo.ArgumentList.Add(argument);
		}
		foreach (string argument in extraArgs)
		{
			startInfo.ArgumentList.Add(argument);
		}
		startInfo.ArgumentList.Add(sourcePath);

		using Process process = Process.Start(startInfo) ?? throw new InvalidOperationException($"Could not start clang at {clangPath}.");
		string stdout = process.StandardOutput.ReadToEnd();
		string stderr = process.StandardError.ReadToEnd();
		process.WaitForExit();

		// Which stream carries the interesting output differs by pass and clang build (-fdump-record-layouts
		// tends to go to stderr; -E always goes to stdout) — concatenating both and letting each parser
		// find what it recognizes is simpler than tracking that per pass.
		return stdout + stderr;
	}
}
