using System.Diagnostics;

namespace AssetRipper.Il2CppRestore.StructDb.Generator;

/// <summary>
/// Runs clang (bundled with every Unity Editor install, under
/// <c>Editor/Data/PlaybackEngines/AndroidPlayer/NDK/toolchains/llvm/prebuilt/&lt;host&gt;/bin/</c>) against
/// the matching <c>libil2cpp</c> headers to measure real struct layouts — guide §10.2. This is an
/// offline, once-per-(Unity version, target triple) tool, never something the restore pipeline itself
/// invokes at runtime.
/// </summary>
public static class StructDbGenerator
{
	/// <summary>
	/// Structs worth forcing clang to lay out. Extend this list as the lifter starts needing more of
	/// them resolved through <see cref="StructDb.TryResolveField"/>.
	/// </summary>
	private static readonly string[] StructsToProbe =
	[
		"Il2CppObject", "Il2CppClass", "Il2CppString", "Il2CppArray", "MethodInfo", "Il2CppTypeDefinition",
	];

	/// <summary>
	/// Generates <c>probe.cpp</c>, runs clang's record-layout dump against it, and returns the parsed DB
	/// — everything but actually writing the JSON to disk (call <see cref="StructDb.Save"/> for that).
	/// </summary>
	/// <param name="clangPath">Full path to clang(.exe) inside the Unity install being probed.</param>
	/// <param name="libil2cppIncludeDir">The Unity install's <c>Editor/Data/il2cpp/libil2cpp</c> directory.</param>
	/// <param name="target">A clang <c>-target</c> triple, e.g. <c>aarch64-linux-android21</c>.</param>
	public static StructDbFile Generate(string clangPath, string libil2cppIncludeDir, string target, string unityVersion, int metadataVersion)
	{
		string workDir = Directory.CreateTempSubdirectory("il2cpp-restore-structdb-").FullName;
		try
		{
			string probePath = Path.Combine(workDir, "probe.cpp");
			File.WriteAllText(probePath, BuildProbeSource());

			string layoutsPath = Path.Combine(workDir, "layouts.txt");
			RunClang(clangPath, libil2cppIncludeDir, target, probePath, layoutsPath, workDir);

			string layoutText = File.ReadAllText(layoutsPath);
			Dictionary<string, StructInfo> structs = ClangLayoutParser.Parse(layoutText);

			return new StructDbFile
			{
				UnityVersion = unityVersion,
				MetadataVersion = metadataVersion,
				Target = target,
				PointerSize = target.StartsWith("i386", StringComparison.Ordinal) || target.StartsWith("armv7", StringComparison.Ordinal) ? 4 : 8,
				GeneratedUtc = DateTime.UtcNow,
				Structs = structs,
			};
		}
		finally
		{
			try
			{
				Directory.Delete(workDir, recursive: true);
			}
			catch (IOException)
			{
				// Best-effort cleanup; a leftover temp directory is harmless.
			}
		}
	}

	private static string BuildProbeSource()
	{
		System.Text.StringBuilder source = new();
		source.AppendLine("// Generated by AssetRipper.Il2CppRestore.StructDb.Generator");
		source.AppendLine("#include \"il2cpp-config.h\"");
		source.AppendLine("#include \"il2cpp-class-internals.h\"");
		source.AppendLine("#include \"il2cpp-object-internals.h\"");
		source.AppendLine("#include \"vm/GlobalMetadataFileInternals.h\"");
		source.AppendLine();
		source.AppendLine("// clang only computes layout for a record actually instantiated somewhere;");
		source.AppendLine("// declaring a pointer to it is not enough.");
		source.AppendLine("template <typename T> struct Force { static T value; };");
		foreach (string name in StructsToProbe)
		{
			source.AppendLine($"Force<{name}> f_{name};");
		}
		source.AppendLine("int main() { return 0; }");
		return source.ToString();
	}

	private static void RunClang(string clangPath, string includeDir, string target, string probePath, string layoutsPath, string workDir)
	{
		ProcessStartInfo startInfo = new(clangPath)
		{
			WorkingDirectory = workDir,
			RedirectStandardOutput = true,
			RedirectStandardError = true,
			UseShellExecute = false,
		};

		// -fsyntax-only prints nothing at all here; only -c (or -emit-llvm -S) makes clang actually
		// compute record layouts rather than just check syntax. Costly to rediscover — noted explicitly
		// per the guide §10.2.
		string[] arguments =
		[
			"-x", "c++", "-std=c++11",
			"-target", target,
			"-I", includeDir,
			"-I", Path.Combine(includeDir, "pch"),
			"-Xclang", "-fdump-record-layouts",
			"-c", "-o", "probe.o", probePath,
		];
		foreach (string argument in arguments)
		{
			startInfo.ArgumentList.Add(argument);
		}

		using Process process = Process.Start(startInfo) ?? throw new InvalidOperationException($"Could not start clang at {clangPath}.");
		string stdout = process.StandardOutput.ReadToEnd();
		string stderr = process.StandardError.ReadToEnd();
		process.WaitForExit();

		// The record layout dump goes to stderr in some clang builds and stdout in others; write both
		// to the same file so ClangLayoutParser sees it regardless.
		File.WriteAllText(layoutsPath, stdout + stderr);
	}
}
