using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Xml.Linq;

[assembly: AssemblyTitle("System.Xml.XDocument")]
[assembly: AssemblyDescription("System.Xml.XDocument")]
[assembly: AssemblyDefaultAlias("System.Xml.XDocument")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyProduct("Microsoft® .NET Framework")]
[assembly: AssemblyCopyright("© Microsoft Corporation.  All rights reserved.")]
[assembly: AssemblyFileVersion("4.6.25714.01")]
[assembly: AssemblyInformationalVersion("4.6.25714.01 built by: dlab-DDVSOWINAGE032. Commit Hash: b7f182415927d3b98445d043e1680c56b9d1f17c")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyMetadata("", "")]
[assembly: AssemblyVersion("4.0.11.0")]
[assembly: TypeForwardedTo(typeof(Extensions))]
[assembly: TypeForwardedTo(typeof(LoadOptions))]
[assembly: TypeForwardedTo(typeof(ReaderOptions))]
[assembly: TypeForwardedTo(typeof(SaveOptions))]
[assembly: TypeForwardedTo(typeof(XAttribute))]
[assembly: TypeForwardedTo(typeof(XCData))]
[assembly: TypeForwardedTo(typeof(XComment))]
[assembly: TypeForwardedTo(typeof(XContainer))]
[assembly: TypeForwardedTo(typeof(XDeclaration))]
[assembly: TypeForwardedTo(typeof(XDocument))]
[assembly: TypeForwardedTo(typeof(XDocumentType))]
[assembly: TypeForwardedTo(typeof(XElement))]
[assembly: TypeForwardedTo(typeof(XName))]
[assembly: TypeForwardedTo(typeof(XNamespace))]
[assembly: TypeForwardedTo(typeof(XNode))]
[assembly: TypeForwardedTo(typeof(XNodeDocumentOrderComparer))]
[assembly: TypeForwardedTo(typeof(XNodeEqualityComparer))]
[assembly: TypeForwardedTo(typeof(XObject))]
[assembly: TypeForwardedTo(typeof(XObjectChange))]
[assembly: TypeForwardedTo(typeof(XObjectChangeEventArgs))]
[assembly: TypeForwardedTo(typeof(XProcessingInstruction))]
[assembly: TypeForwardedTo(typeof(XStreamingElement))]
[assembly: TypeForwardedTo(typeof(XText))]
