using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text;
using DecompTools.Decompiler.CSharp;
using DecompTools.Decompiler.CSharp.OutputVisitor;
using DecompTools.Decompiler.CSharp.Syntax;
using DecompTools.Decompiler.IL;
using DecompTools.Decompiler.Metadata;
using DecompTools.Decompiler.TypeSystem;
using DecompTools.Decompiler.Util;

namespace DecompTools.Decompiler.DebugInfo;

public class PortablePdbWriter
{
	private static readonly Guid CSharpLanguageGuid = new Guid("3f5162f8-07c6-11d3-9053-00c04fa302a1");

	private static readonly Guid DebugInfoEmbeddedSource = new Guid("0e8a571b-6926-466e-b4ad-8ab04611f5fe");

	private static readonly Guid MethodSteppingInformationBlobId = new Guid("54FD2AC5-E925-401A-9C2A-F94F171072F8");

	private static readonly Guid HashAlgorithmSHA1 = new Guid("ff1816ec-aa5e-4d10-87f7-6f4963833460");

	private static readonly Guid HashAlgorithmSHA256 = new Guid("8829d00f-11b8-4213-878b-770e8597ac16");

	private static readonly FileVersionInfo decompilerVersion = FileVersionInfo.GetVersionInfo(typeof(CSharpDecompiler).Assembly.Location);

	public static bool HasCodeViewDebugDirectoryEntry(PEFile file)
	{
		return file.Reader.ReadDebugDirectory().Any((DebugDirectoryEntry entry) => entry.Type == DebugDirectoryEntryType.CodeView);
	}

	public static void WritePdb(PEFile file, CSharpDecompiler decompiler, DecompilerSettings settings, Stream targetStream, bool noLogo = false)
	{
		MetadataBuilder metadata = new MetadataBuilder();
		MetadataReader reader = file.Metadata;
		MethodDefinitionHandle entryPoint = MetadataTokens.MethodDefinitionHandle(file.Reader.PEHeaders.CorHeader.EntryPointTokenOrRelativeVirtualAddress);
		Dictionary<MethodDefinitionHandle, (DocumentHandle Document, BlobHandle SequencePoints)> sequencePointBlobs = new Dictionary<MethodDefinitionHandle, (DocumentHandle, BlobHandle)>();
		List<SequencePoint> list = new List<SequencePoint>();
		List<(MethodDefinitionHandle, MethodDefinitionHandle)> list2 = new List<(MethodDefinitionHandle, MethodDefinitionHandle)>();
		List<(DocumentHandle, GuidHandle, BlobHandle)> list3 = new List<(DocumentHandle, GuidHandle, BlobHandle)>();
		List<(MethodDefinitionHandle, GuidHandle, BlobHandle)> list4 = new List<(MethodDefinitionHandle, GuidHandle, BlobHandle)>();
		ImportScopeHandle globalImportScope = metadata.AddImportScope(default(ImportScopeHandle), default(BlobHandle));
		foreach (TypeDefinitionHandle topLevelTypeDefinition in reader.GetTopLevelTypeDefinitions())
		{
			TypeDefinition typeDefinition = reader.GetTypeDefinition(topLevelTypeDefinition);
			SyntaxTree syntaxTree = decompiler.DecompileTypes(new TypeDefinitionHandle[1] { topLevelTypeDefinition });
			if (!syntaxTree.HasChildren)
			{
				continue;
			}
			if (!noLogo)
			{
				syntaxTree.InsertChildAfter(null, new Comment(" PDB and source generated by DecompTools.Decompiler " + decompilerVersion.FileVersion), Roles.Comment);
			}
			string sourceText = SyntaxTreeToString(syntaxTree, settings);
			Dictionary<ILFunction, List<SequencePoint>> dictionary = decompiler.CreateSequencePoints(syntaxTree);
			DebugInfoGenerator debugInfoGenerator = new DebugInfoGenerator(decompiler.TypeSystem);
			syntaxTree.AcceptVisitor(debugInfoGenerator);
			lock (metadata)
			{
				BlobHandle item = WriteSourceToBlob(metadata, sourceText, out var sourceCheckSum);
				BlobHandle orAddDocumentName = metadata.GetOrAddDocumentName(typeDefinition.GetFullTypeName(reader).ReflectionName.Replace('.', Path.DirectorySeparatorChar) + ".cs");
				DocumentHandle documentHandle = metadata.AddDocument(orAddDocumentName, metadata.GetOrAddGuid(HashAlgorithmSHA256), metadata.GetOrAddBlob(sourceCheckSum), metadata.GetOrAddGuid(CSharpLanguageGuid));
				list3.Add((documentHandle, metadata.GetOrAddGuid(DebugInfoEmbeddedSource), item));
				debugInfoGenerator.Generate(metadata, globalImportScope);
				foreach (ILFunction function in debugInfoGenerator.Functions)
				{
					IMethod method = function.MoveNextMethod ?? function.Method;
					MethodDefinitionHandle methodDefinitionHandle = (MethodDefinitionHandle)method.MetadataToken;
					dictionary.TryGetValue(function, out var value);
					ProcessMethod(methodDefinitionHandle, documentHandle, value, syntaxTree);
					if (function.MoveNextMethod != null)
					{
						list2.Add(((MethodDefinitionHandle)function.MoveNextMethod.MetadataToken, (MethodDefinitionHandle)function.Method.MetadataToken));
					}
					if (function.IsAsync)
					{
						list4.Add((methodDefinitionHandle, metadata.GetOrAddGuid(MethodSteppingInformationBlobId), metadata.GetOrAddBlob(function.AsyncDebugInfo.BuildBlob(methodDefinitionHandle))));
					}
				}
			}
		}
		foreach (MethodDefinitionHandle methodDefinition3 in reader.MethodDefinitions)
		{
			MethodDefinition methodDefinition = reader.GetMethodDefinition(methodDefinition3);
			if (sequencePointBlobs.TryGetValue(methodDefinition3, out (DocumentHandle, BlobHandle) value2))
			{
				metadata.AddMethodDebugInformation(value2.Item1, value2.Item2);
			}
			else
			{
				metadata.AddMethodDebugInformation(default(DocumentHandle), default(BlobHandle));
			}
		}
		list2.SortBy<(MethodDefinitionHandle, MethodDefinitionHandle), MethodDefinitionHandle>(((MethodDefinitionHandle MoveNextMethod, MethodDefinitionHandle KickoffMethod) row) => row.MoveNextMethod);
		foreach (var item2 in list2)
		{
			metadata.AddStateMachineMethod(item2.Item1, item2.Item2);
		}
		list4.SortBy<(MethodDefinitionHandle, GuidHandle, BlobHandle), MethodDefinitionHandle>(((MethodDefinitionHandle Parent, GuidHandle Guid, BlobHandle Blob) row) => row.Parent);
		foreach (var item3 in list4)
		{
			metadata.AddCustomDebugInformation(item3.Item1, item3.Item2, item3.Item3);
		}
		list3.SortBy<(DocumentHandle, GuidHandle, BlobHandle), DocumentHandle>(((DocumentHandle Parent, GuidHandle Guid, BlobHandle Blob) row) => row.Parent);
		foreach (var item4 in list3)
		{
			metadata.AddCustomDebugInformation(item4.Item1, item4.Item2, item4.Item3);
		}
		DebugDirectoryEntry entry = file.Reader.ReadDebugDirectory().FirstOrDefault((DebugDirectoryEntry dir) => dir.Type == DebugDirectoryEntryType.CodeView);
		BlobContentId contentId = new BlobContentId(file.Reader.ReadCodeViewDebugDirectoryData(entry).Guid, entry.Stamp);
		PortablePdbBuilder portablePdbBuilder = new PortablePdbBuilder(metadata, GetRowCounts(reader), entryPoint, (IEnumerable<Blob> blobs) => contentId);
		BlobBuilder blobBuilder = new BlobBuilder();
		portablePdbBuilder.Serialize(blobBuilder);
		blobBuilder.WriteContentTo(targetStream);
		void ProcessMethod(MethodDefinitionHandle methodDefinitionHandle2, DocumentHandle document, List<SequencePoint> sequencePoints, SyntaxTree syntaxTree2)
		{
			MethodDefinition methodDefinition2 = reader.GetMethodDefinition(methodDefinitionHandle2);
			int localSignatureRowId;
			if (methodDefinition2.RelativeVirtualAddress != 0)
			{
				MethodBodyBlock methodBody = file.Reader.GetMethodBody(methodDefinition2.RelativeVirtualAddress);
				localSignatureRowId = ((!methodBody.LocalSignature.IsNil) ? MetadataTokens.GetRowNumber(methodBody.LocalSignature) : 0);
			}
			else
			{
				MethodBodyBlock methodBody = null;
				localSignatureRowId = 0;
			}
			if (sequencePoints != null && sequencePoints.Count > 0)
			{
				sequencePointBlobs.Add(methodDefinitionHandle2, (document, EncodeSequencePoints(metadata, localSignatureRowId, sequencePoints)));
			}
			else
			{
				sequencePointBlobs.Add(methodDefinitionHandle2, (default(DocumentHandle), default(BlobHandle)));
			}
		}
	}

	private static BlobHandle WriteSourceToBlob(MetadataBuilder metadata, string sourceText, out byte[] sourceCheckSum)
	{
		//IL_0016: Unknown result type (might be due to invalid IL or missing references)
		//IL_001c: Expected O, but got Unknown
		BlobBuilder blobBuilder = new BlobBuilder();
		using (MemoryStream memoryStream = new MemoryStream())
		{
			DeflateStream val = new DeflateStream((Stream)memoryStream, (CompressionLevel)0, true);
			byte[] bytes = Encoding.UTF8.GetBytes(sourceText);
			((Stream)(object)val).Write(bytes, 0, bytes.Length);
			((Stream)(object)val).Close();
			byte[] buffer = memoryStream.ToArray();
			blobBuilder.WriteInt32(bytes.Length);
			blobBuilder.WriteBytes(buffer);
			SHA256 val2 = SHA256.Create();
			try
			{
				sourceCheckSum = ((HashAlgorithm)val2).ComputeHash(bytes);
			}
			finally
			{
				((IDisposable)val2)?.Dispose();
			}
		}
		return metadata.GetOrAddBlob(blobBuilder);
	}

	private static BlobHandle EncodeSequencePoints(MetadataBuilder metadata, int localSignatureRowId, List<SequencePoint> sequencePoints)
	{
		if (sequencePoints.Count == 0)
		{
			return default(BlobHandle);
		}
		BlobBuilder blobBuilder = new BlobBuilder();
		blobBuilder.WriteCompressedInteger(localSignatureRowId);
		int num = -1;
		int num2 = -1;
		int num3 = -1;
		checked
		{
			for (int i = 0; i < sequencePoints.Count; i++)
			{
				SequencePoint sequencePoint = sequencePoints[i];
				if (i > 0)
				{
					blobBuilder.WriteCompressedInteger(sequencePoint.Offset - num);
				}
				else
				{
					blobBuilder.WriteCompressedInteger(sequencePoint.Offset);
				}
				num = sequencePoint.Offset;
				if (sequencePoint.IsHidden)
				{
					blobBuilder.WriteInt16(0);
					continue;
				}
				int num4 = sequencePoint.EndLine - sequencePoint.StartLine;
				int value = sequencePoint.EndColumn - sequencePoint.StartColumn;
				blobBuilder.WriteCompressedInteger(num4);
				if (num4 == 0)
				{
					blobBuilder.WriteCompressedInteger(value);
				}
				else
				{
					blobBuilder.WriteCompressedSignedInteger(value);
				}
				if (num2 < 0)
				{
					blobBuilder.WriteCompressedInteger(sequencePoint.StartLine);
					blobBuilder.WriteCompressedInteger(sequencePoint.StartColumn);
				}
				else
				{
					blobBuilder.WriteCompressedSignedInteger(sequencePoint.StartLine - num2);
					blobBuilder.WriteCompressedSignedInteger(sequencePoint.StartColumn - num3);
				}
				num2 = sequencePoint.StartLine;
				num3 = sequencePoint.StartColumn;
			}
			return metadata.GetOrAddBlob(blobBuilder);
		}
	}

	private static ImmutableArray<int> GetRowCounts(MetadataReader reader)
	{
		ImmutableArray<int>.Builder builder = ImmutableArray.CreateBuilder<int>(MetadataTokens.TableCount);
		for (int i = 0; i < MetadataTokens.TableCount; i = checked(i + 1))
		{
			builder.Add(reader.GetTableRowCount((TableIndex)checked((byte)i)));
		}
		return builder.MoveToImmutable();
	}

	private static string SyntaxTreeToString(SyntaxTree syntaxTree, DecompilerSettings settings)
	{
		StringWriter stringWriter = new StringWriter();
		TokenWriter writer = new TextWriterTokenWriter(stringWriter);
		syntaxTree.AcceptVisitor(new InsertParenthesesVisitor
		{
			InsertParenthesesForReadability = true
		});
		writer = TokenWriter.WrapInWriterThatSetsLocationsInAST(writer);
		syntaxTree.AcceptVisitor(new CSharpOutputVisitor(writer, settings.CSharpFormattingOptions));
		return stringWriter.ToString();
	}
}
