<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Composition.Hosting</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net40</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\System.Composition.Runtime\System.Composition.Runtime.csproj" />
    <ProjectReference Include="..\System.Reflection\System.Reflection.csproj" />
    <ProjectReference Include="..\System.Linq.Expressions\System.Linq.Expressions.csproj" />
    <ProjectReference Include="..\System.Collections\System.Collections.csproj" />
    <ProjectReference Include="..\System.Resources.ResourceManager\System.Resources.ResourceManager.csproj" />
    <ProjectReference Include="..\System.Globalization\System.Globalization.csproj" />
    <ProjectReference Include="..\System.Linq\System.Linq.csproj" />
    <ProjectReference Include="..\System.Reflection.Extensions\System.Reflection.Extensions.csproj" />
    <ProjectReference Include="..\System.Threading\System.Threading.csproj" />
    <ProjectReference Include="..\System.ObjectModel\System.ObjectModel.csproj" />
  </ItemGroup>
</Project>