<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>System.Composition.Hosting</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\System.Composition.Runtime\System.Composition.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- System.Lazy<T,TMetadata> lives here on .NET Framework -->
    <Reference Include="System.ComponentModel.Composition" />
  </ItemGroup>
</Project>