namespace SpirV
{
	public enum Decoration : uint
	{
		RelaxedPrecision = 0u,
		SpecId = 1u,
		Block = 2u,
		BufferBlock = 3u,
		RowMajor = 4u,
		ColMajor = 5u,
		ArrayStride = 6u,
		MatrixStride = 7u,
		GLSLShared = 8u,
		GLSLPacked = 9u,
		CPacked = 10u,
		BuiltIn = 11u,
		NoPerspective = 13u,
		Flat = 14u,
		Patch = 0xF,
		Centroid = 0x10,
		Sample = 17u,
		Invariant = 18u,
		Restrict = 19u,
		Aliased = 20u,
		Volatile = 21u,
		Constant = 22u,
		Coherent = 23u,
		NonWritable = 24u,
		NonReadable = 25u,
		Uniform = 26u,
		SaturatedConversion = 28u,
		Stream = 29u,
		Location = 30u,
		Component = 0x1F,
		Index = 0x20,
		Binding = 33u,
		DescriptorSet = 34u,
		Offset = 35u,
		XfbBuffer = 36u,
		XfbStride = 37u,
		FuncParamAttr = 38u,
		FPRoundingMode = 39u,
		FPFastMathMode = 40u,
		LinkageAttributes = 41u,
		NoContraction = 42u,
		InputAttachmentIndex = 43u,
		Alignment = 44u,
		MaxByteOffset = 45u,
		AlignmentId = 46u,
		MaxByteOffsetId = 47u,
		ExplicitInterpAMD = 4999u,
		OverrideCoverageNV = 5248u,
		PassthroughNV = 5250u,
		ViewportRelativeNV = 5252u,
		SecondaryViewportRelativeNV = 5256u
	}
}
