namespace SpirV
{
	public enum ExecutionMode : uint
	{
		Invocations = 0u,
		SpacingEqual = 1u,
		SpacingFractionalEven = 2u,
		SpacingFractionalOdd = 3u,
		VertexOrderCw = 4u,
		VertexOrderCcw = 5u,
		PixelCenterInteger = 6u,
		OriginUpperLeft = 7u,
		OriginLowerLeft = 8u,
		EarlyFragmentTests = 9u,
		PointMode = 10u,
		Xfb = 11u,
		DepthReplacing = 12u,
		DepthGreater = 14u,
		DepthLess = 0xF,
		DepthUnchanged = 0x10,
		LocalSize = 17u,
		LocalSizeHint = 18u,
		InputPoints = 19u,
		InputLines = 20u,
		InputLinesAdjacency = 21u,
		Triangles = 22u,
		InputTrianglesAdjacency = 23u,
		Quads = 24u,
		Isolines = 25u,
		OutputVertices = 26u,
		OutputPoints = 27u,
		OutputLineStrip = 28u,
		OutputTriangleStrip = 29u,
		VecTypeHint = 30u,
		ContractionOff = 0x1F,
		Initializer = 33u,
		Finalizer = 34u,
		SubgroupSize = 35u,
		SubgroupsPerWorkgroup = 36u,
		SubgroupsPerWorkgroupId = 37u,
		LocalSizeId = 38u,
		LocalSizeHintId = 39u,
		PostDepthCoverage = 4446u,
		StencilRefReplacingEXT = 5027u
	}
}
