<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mono.Cecil</AssemblyName>
    <RootNamespace />
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS0108;CS0109;CS0114;CS0162;CS0164;CS0169;CS0219;CS0414;CS0618;CS0649;CS1030;CS1717;CS3021;SYSLIB0011</NoWarn>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Core"><HintPath>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll</HintPath></Reference>
  </ItemGroup>
</Project>
