using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Cpp2ILInjected;

[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyConfigurationAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyDescriptionAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyTitleAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyCompanyAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyTrademarkAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyCopyrightAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(AssemblyProductAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: RuntimeCompatibility]
[assembly: Attribute(Type = typeof(DebuggableAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Attribute(Type = typeof(InternalsVisibleToAttribute), RVA = "0x73BEE0", Offset = "0x73BEE0")]
[assembly: Token(Token = "0x20000001")]
[assembly: AssemblyVersion("1.0.0.0")]
